title: Angry Cats!
author: George
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This will tell you everything about hungry cats and how they misbehave and do terrible things.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
